# Generated by Django 5.2 on 2025-05-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_common', models.CharField(max_length=255)),
                ('name_official', models.CharField(max_length=255)),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('cca3', models.CharField(max_length=3, unique=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('flag_png', models.URLField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.BigIntegerField(default=0)),
                ('area', models.FloatField(blank=True, null=True)),
                ('independent', models.BooleanField(default=True)),
                ('un_member', models.BooleanField(default=True)),
                ('landlocked', models.BooleanField(default=False)),
                ('currencies', models.JSONField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('latlng', models.JSONField(blank=True, null=True)),
                ('borders', models.JSONField(blank=True, null=True)),
                ('timezones', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name_common'],
            },
        ),
    ]
