# Generated by Django 5.2 on 2025-05-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='cca2',
            new_name='alpha2code',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='cca3',
            new_name='alpha3code',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='flag_emoji',
            new_name='numeric_code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='flag_png',
        ),
        migrations.RemoveField(
            model_name='country',
            name='independent',
        ),
        migrations.RemoveField(
            model_name='country',
            name='landlocked',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_common',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_official',
        ),
        migrations.RemoveField(
            model_name='country',
            name='un_member',
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='native_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='borders',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='currencies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='latlng',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='subregion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='timezones',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
